package com.webterm.terminal.model;

/** 只有 WS 权威投影连续性错误可以产生这些故障。 */
public enum ProjectionFault {
  IDENTITY_MISMATCH,
  LAYOUT_EPOCH_MISMATCH,
  REVISION_GAP,
  HISTORY_GENERATION_MISMATCH,
  PROMOTION_BODY_INVARIANT_FAILURE,
  INVALID_BASELINE,
  INVALID_IDENTITY,
  INVALID_GENERATION,
  INVALID_GEOMETRY,
  SCREEN_LINE_COUNT_MISMATCH,
  SCREEN_LAYOUT_COUNT_MISMATCH,
  HISTORY_BINDING_COUNT_MISMATCH,
  HISTORY_SEQ_OUT_OF_ORDER,
  HISTORY_SEQ_OUT_OF_EXTENT,
  DUPLICATE_HISTORY_KEY,
  DUPLICATE_ACTIVE_KEY,
  ACTIVE_HISTORY_KEY_CONFLICT,
  LINE_COLUMN_COUNT_MISMATCH,
  INVALID_LINE_BODY,
  BASELINE_BODY_CONFLICT,
  INVALID_DICTIONARY,
  MAPPER_FAILURE,
  MODEL_REJECTED_BASELINE,
  INVALID_SCREEN_MUTATION,
  INVALID_HISTORY_MUTATION
}
