// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: shared/proto/terminal_history.proto

package generatedv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LineBodyBatchStatus int32

const (
	LineBodyBatchStatus_LINE_BODY_BATCH_STATUS_UNSPECIFIED  LineBodyBatchStatus = 0
	LineBodyBatchStatus_LINE_BODY_BATCH_STATUS_OK           LineBodyBatchStatus = 1
	LineBodyBatchStatus_LINE_BODY_BATCH_STATUS_STALE        LineBodyBatchStatus = 2
	LineBodyBatchStatus_LINE_BODY_BATCH_STATUS_SESSION_GONE LineBodyBatchStatus = 3
	LineBodyBatchStatus_LINE_BODY_BATCH_STATUS_RETRYABLE    LineBodyBatchStatus = 4
)

// Enum value maps for LineBodyBatchStatus.
var (
	LineBodyBatchStatus_name = map[int32]string{
		0: "LINE_BODY_BATCH_STATUS_UNSPECIFIED",
		1: "LINE_BODY_BATCH_STATUS_OK",
		2: "LINE_BODY_BATCH_STATUS_STALE",
		3: "LINE_BODY_BATCH_STATUS_SESSION_GONE",
		4: "LINE_BODY_BATCH_STATUS_RETRYABLE",
	}
	LineBodyBatchStatus_value = map[string]int32{
		"LINE_BODY_BATCH_STATUS_UNSPECIFIED":  0,
		"LINE_BODY_BATCH_STATUS_OK":           1,
		"LINE_BODY_BATCH_STATUS_STALE":        2,
		"LINE_BODY_BATCH_STATUS_SESSION_GONE": 3,
		"LINE_BODY_BATCH_STATUS_RETRYABLE":    4,
	}
)

func (x LineBodyBatchStatus) Enum() *LineBodyBatchStatus {
	p := new(LineBodyBatchStatus)
	*p = x
	return p
}

func (x LineBodyBatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LineBodyBatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_terminal_history_proto_enumTypes[0].Descriptor()
}

func (LineBodyBatchStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_terminal_history_proto_enumTypes[0]
}

func (x LineBodyBatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LineBodyBatchStatus.Descriptor instead.
func (LineBodyBatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_terminal_history_proto_rawDescGZIP(), []int{0}
}

// HTTP 历史正文批量拉取（不经 ScreenEnvelope）。
type LineBodyBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Keys          []*LineKey             `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineBodyBatchRequest) Reset() {
	*x = LineBodyBatchRequest{}
	mi := &file_shared_proto_terminal_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineBodyBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineBodyBatchRequest) ProtoMessage() {}

func (x *LineBodyBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_terminal_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineBodyBatchRequest.ProtoReflect.Descriptor instead.
func (*LineBodyBatchRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_terminal_history_proto_rawDescGZIP(), []int{0}
}

func (x *LineBodyBatchRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *LineBodyBatchRequest) GetKeys() []*LineKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type LineBodyBatchResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceId        string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Bodies            []*LineBodyRecord      `protobuf:"bytes,2,rep,name=bodies,proto3" json:"bodies,omitempty"`
	MissingKeys       []*LineKey             `protobuf:"bytes,3,rep,name=missing_keys,json=missingKeys,proto3" json:"missing_keys,omitempty"`
	Dictionary        *Dictionary            `protobuf:"bytes,4,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	Status            LineBodyBatchStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=webterm.terminal.screen.v3.LineBodyBatchStatus" json:"status,omitempty"`
	LayoutEpoch       uint64                 `protobuf:"varint,6,opt,name=layout_epoch,json=layoutEpoch,proto3" json:"layout_epoch,omitempty"`
	HistoryGeneration uint64                 `protobuf:"varint,7,opt,name=history_generation,json=historyGeneration,proto3" json:"history_generation,omitempty"`
	RetryAfterMs      uint32                 `protobuf:"varint,8,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LineBodyBatchResponse) Reset() {
	*x = LineBodyBatchResponse{}
	mi := &file_shared_proto_terminal_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineBodyBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineBodyBatchResponse) ProtoMessage() {}

func (x *LineBodyBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_terminal_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineBodyBatchResponse.ProtoReflect.Descriptor instead.
func (*LineBodyBatchResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_terminal_history_proto_rawDescGZIP(), []int{1}
}

func (x *LineBodyBatchResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *LineBodyBatchResponse) GetBodies() []*LineBodyRecord {
	if x != nil {
		return x.Bodies
	}
	return nil
}

func (x *LineBodyBatchResponse) GetMissingKeys() []*LineKey {
	if x != nil {
		return x.MissingKeys
	}
	return nil
}

func (x *LineBodyBatchResponse) GetDictionary() *Dictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

func (x *LineBodyBatchResponse) GetStatus() LineBodyBatchStatus {
	if x != nil {
		return x.Status
	}
	return LineBodyBatchStatus_LINE_BODY_BATCH_STATUS_UNSPECIFIED
}

func (x *LineBodyBatchResponse) GetLayoutEpoch() uint64 {
	if x != nil {
		return x.LayoutEpoch
	}
	return 0
}

func (x *LineBodyBatchResponse) GetHistoryGeneration() uint64 {
	if x != nil {
		return x.HistoryGeneration
	}
	return 0
}

func (x *LineBodyBatchResponse) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_shared_proto_terminal_history_proto protoreflect.FileDescriptor

const file_shared_proto_terminal_history_proto_rawDesc = "" +
	"\n" +
	"#shared/proto/terminal_history.proto\x12\x1awebterm.terminal.screen.v3\x1a%shared/proto/terminal_screen_v3.proto\"p\n" +
	"\x14LineBodyBatchRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x127\n" +
	"\x04keys\x18\x02 \x03(\v2#.webterm.terminal.screen.v3.LineKeyR\x04keys\"\xcd\x03\n" +
	"\x15LineBodyBatchResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12B\n" +
	"\x06bodies\x18\x02 \x03(\v2*.webterm.terminal.screen.v3.LineBodyRecordR\x06bodies\x12F\n" +
	"\fmissing_keys\x18\x03 \x03(\v2#.webterm.terminal.screen.v3.LineKeyR\vmissingKeys\x12F\n" +
	"\n" +
	"dictionary\x18\x04 \x01(\v2&.webterm.terminal.screen.v3.DictionaryR\n" +
	"dictionary\x12G\n" +
	"\x06status\x18\x05 \x01(\x0e2/.webterm.terminal.screen.v3.LineBodyBatchStatusR\x06status\x12!\n" +
	"\flayout_epoch\x18\x06 \x01(\x04R\vlayoutEpoch\x12-\n" +
	"\x12history_generation\x18\a \x01(\x04R\x11historyGeneration\x12$\n" +
	"\x0eretry_after_ms\x18\b \x01(\rR\fretryAfterMs*\xcd\x01\n" +
	"\x13LineBodyBatchStatus\x12&\n" +
	"\"LINE_BODY_BATCH_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19LINE_BODY_BATCH_STATUS_OK\x10\x01\x12 \n" +
	"\x1cLINE_BODY_BATCH_STATUS_STALE\x10\x02\x12'\n" +
	"#LINE_BODY_BATCH_STATUS_SESSION_GONE\x10\x03\x12$\n" +
	" LINE_BODY_BATCH_STATUS_RETRYABLE\x10\x04Bv\n" +
	"'com.webterm.terminal.protocol.generatedB\x14TerminalHistoryProtoH\x03Z3webterm/go-core/internal/screenprotocol/generatedv3b\x06proto3"

var (
	file_shared_proto_terminal_history_proto_rawDescOnce sync.Once
	file_shared_proto_terminal_history_proto_rawDescData []byte
)

func file_shared_proto_terminal_history_proto_rawDescGZIP() []byte {
	file_shared_proto_terminal_history_proto_rawDescOnce.Do(func() {
		file_shared_proto_terminal_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_terminal_history_proto_rawDesc), len(file_shared_proto_terminal_history_proto_rawDesc)))
	})
	return file_shared_proto_terminal_history_proto_rawDescData
}

var file_shared_proto_terminal_history_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_terminal_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_terminal_history_proto_goTypes = []any{
	(LineBodyBatchStatus)(0),      // 0: webterm.terminal.screen.v3.LineBodyBatchStatus
	(*LineBodyBatchRequest)(nil),  // 1: webterm.terminal.screen.v3.LineBodyBatchRequest
	(*LineBodyBatchResponse)(nil), // 2: webterm.terminal.screen.v3.LineBodyBatchResponse
	(*LineKey)(nil),               // 3: webterm.terminal.screen.v3.LineKey
	(*LineBodyRecord)(nil),        // 4: webterm.terminal.screen.v3.LineBodyRecord
	(*Dictionary)(nil),            // 5: webterm.terminal.screen.v3.Dictionary
}
var file_shared_proto_terminal_history_proto_depIdxs = []int32{
	3, // 0: webterm.terminal.screen.v3.LineBodyBatchRequest.keys:type_name -> webterm.terminal.screen.v3.LineKey
	4, // 1: webterm.terminal.screen.v3.LineBodyBatchResponse.bodies:type_name -> webterm.terminal.screen.v3.LineBodyRecord
	3, // 2: webterm.terminal.screen.v3.LineBodyBatchResponse.missing_keys:type_name -> webterm.terminal.screen.v3.LineKey
	5, // 3: webterm.terminal.screen.v3.LineBodyBatchResponse.dictionary:type_name -> webterm.terminal.screen.v3.Dictionary
	0, // 4: webterm.terminal.screen.v3.LineBodyBatchResponse.status:type_name -> webterm.terminal.screen.v3.LineBodyBatchStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shared_proto_terminal_history_proto_init() }
func file_shared_proto_terminal_history_proto_init() {
	if File_shared_proto_terminal_history_proto != nil {
		return
	}
	file_shared_proto_terminal_screen_v3_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_terminal_history_proto_rawDesc), len(file_shared_proto_terminal_history_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_terminal_history_proto_goTypes,
		DependencyIndexes: file_shared_proto_terminal_history_proto_depIdxs,
		EnumInfos:         file_shared_proto_terminal_history_proto_enumTypes,
		MessageInfos:      file_shared_proto_terminal_history_proto_msgTypes,
	}.Build()
	File_shared_proto_terminal_history_proto = out.File
	file_shared_proto_terminal_history_proto_goTypes = nil
	file_shared_proto_terminal_history_proto_depIdxs = nil
}
