package com.webterm.terminal.protocol;

/** Baseline wire 校验失败的稳定分类；不得包含终端正文。 */
public enum BaselineFaultCode {
  INVALID_IDENTITY,
  INVALID_GENERATION,
  INVALID_GEOMETRY,
  SCREEN_LINE_COUNT_MISMATCH,
  SCREEN_LAYOUT_COUNT_MISMATCH,
  HISTORY_BINDING_COUNT_MISMATCH,
  HISTORY_SEQ_OUT_OF_ORDER,
  HISTORY_SEQ_OUT_OF_EXTENT,
  DUPLICATE_HISTORY_KEY,
  DUPLICATE_ACTIVE_KEY,
  ACTIVE_HISTORY_KEY_CONFLICT,
  LINE_COLUMN_COUNT_MISMATCH,
  INVALID_LINE_BODY,
  BASELINE_BODY_CONFLICT,
  INVALID_DICTIONARY,
  MAPPER_FAILURE,
  MODEL_REJECTED_BASELINE
}
