// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: shared/proto/terminal_history.proto

package generatedv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryRangeStatus int32

const (
	HistoryRangeStatus_HISTORY_RANGE_STATUS_UNSPECIFIED      HistoryRangeStatus = 0
	HistoryRangeStatus_HISTORY_RANGE_STATUS_OK               HistoryRangeStatus = 1
	HistoryRangeStatus_HISTORY_RANGE_STATUS_STALE_GENERATION HistoryRangeStatus = 2
	HistoryRangeStatus_HISTORY_RANGE_STATUS_SESSION_GONE     HistoryRangeStatus = 3
	HistoryRangeStatus_HISTORY_RANGE_STATUS_RETRYABLE        HistoryRangeStatus = 4
)

// Enum value maps for HistoryRangeStatus.
var (
	HistoryRangeStatus_name = map[int32]string{
		0: "HISTORY_RANGE_STATUS_UNSPECIFIED",
		1: "HISTORY_RANGE_STATUS_OK",
		2: "HISTORY_RANGE_STATUS_STALE_GENERATION",
		3: "HISTORY_RANGE_STATUS_SESSION_GONE",
		4: "HISTORY_RANGE_STATUS_RETRYABLE",
	}
	HistoryRangeStatus_value = map[string]int32{
		"HISTORY_RANGE_STATUS_UNSPECIFIED":      0,
		"HISTORY_RANGE_STATUS_OK":               1,
		"HISTORY_RANGE_STATUS_STALE_GENERATION": 2,
		"HISTORY_RANGE_STATUS_SESSION_GONE":     3,
		"HISTORY_RANGE_STATUS_RETRYABLE":        4,
	}
)

func (x HistoryRangeStatus) Enum() *HistoryRangeStatus {
	p := new(HistoryRangeStatus)
	*p = x
	return p
}

func (x HistoryRangeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryRangeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_terminal_history_proto_enumTypes[0].Descriptor()
}

func (HistoryRangeStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_terminal_history_proto_enumTypes[0]
}

func (x HistoryRangeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryRangeStatus.Descriptor instead.
func (HistoryRangeStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_terminal_history_proto_rawDescGZIP(), []int{0}
}

type HistoryRangeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            HistoryRangeStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=webterm.terminal.screen.v2.HistoryRangeStatus" json:"status,omitempty"`
	HistoryGeneration uint64                 `protobuf:"varint,2,opt,name=history_generation,json=historyGeneration,proto3" json:"history_generation,omitempty"`
	CurrentExtent     *HistoryExtent         `protobuf:"bytes,3,opt,name=current_extent,json=currentExtent,proto3" json:"current_extent,omitempty"`
	Lines             []*LineData            `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	Dictionary        *Dictionary            `protobuf:"bytes,5,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	RetryAfterMs      uint32                 `protobuf:"varint,6,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HistoryRangeResponse) Reset() {
	*x = HistoryRangeResponse{}
	mi := &file_shared_proto_terminal_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRangeResponse) ProtoMessage() {}

func (x *HistoryRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_terminal_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRangeResponse.ProtoReflect.Descriptor instead.
func (*HistoryRangeResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_terminal_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryRangeResponse) GetStatus() HistoryRangeStatus {
	if x != nil {
		return x.Status
	}
	return HistoryRangeStatus_HISTORY_RANGE_STATUS_UNSPECIFIED
}

func (x *HistoryRangeResponse) GetHistoryGeneration() uint64 {
	if x != nil {
		return x.HistoryGeneration
	}
	return 0
}

func (x *HistoryRangeResponse) GetCurrentExtent() *HistoryExtent {
	if x != nil {
		return x.CurrentExtent
	}
	return nil
}

func (x *HistoryRangeResponse) GetLines() []*LineData {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *HistoryRangeResponse) GetDictionary() *Dictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

func (x *HistoryRangeResponse) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_shared_proto_terminal_history_proto protoreflect.FileDescriptor

const file_shared_proto_terminal_history_proto_rawDesc = "" +
	"\n" +
	"#shared/proto/terminal_history.proto\x12\x1awebterm.terminal.screen.v2\x1a%shared/proto/terminal_screen_v2.proto\"\x89\x03\n" +
	"\x14HistoryRangeResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..webterm.terminal.screen.v2.HistoryRangeStatusR\x06status\x12-\n" +
	"\x12history_generation\x18\x02 \x01(\x04R\x11historyGeneration\x12P\n" +
	"\x0ecurrent_extent\x18\x03 \x01(\v2).webterm.terminal.screen.v2.HistoryExtentR\rcurrentExtent\x12:\n" +
	"\x05lines\x18\x04 \x03(\v2$.webterm.terminal.screen.v2.LineDataR\x05lines\x12F\n" +
	"\n" +
	"dictionary\x18\x05 \x01(\v2&.webterm.terminal.screen.v2.DictionaryR\n" +
	"dictionary\x12$\n" +
	"\x0eretry_after_ms\x18\x06 \x01(\rR\fretryAfterMs*\xcd\x01\n" +
	"\x12HistoryRangeStatus\x12$\n" +
	" HISTORY_RANGE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17HISTORY_RANGE_STATUS_OK\x10\x01\x12)\n" +
	"%HISTORY_RANGE_STATUS_STALE_GENERATION\x10\x02\x12%\n" +
	"!HISTORY_RANGE_STATUS_SESSION_GONE\x10\x03\x12\"\n" +
	"\x1eHISTORY_RANGE_STATUS_RETRYABLE\x10\x04Bt\n" +
	"'com.webterm.terminal.protocol.generatedB\x14TerminalHistoryProtoZ3webterm/go-core/internal/screenprotocol/generatedv2b\x06proto3"

var (
	file_shared_proto_terminal_history_proto_rawDescOnce sync.Once
	file_shared_proto_terminal_history_proto_rawDescData []byte
)

func file_shared_proto_terminal_history_proto_rawDescGZIP() []byte {
	file_shared_proto_terminal_history_proto_rawDescOnce.Do(func() {
		file_shared_proto_terminal_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_terminal_history_proto_rawDesc), len(file_shared_proto_terminal_history_proto_rawDesc)))
	})
	return file_shared_proto_terminal_history_proto_rawDescData
}

var file_shared_proto_terminal_history_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_terminal_history_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_proto_terminal_history_proto_goTypes = []any{
	(HistoryRangeStatus)(0),      // 0: webterm.terminal.screen.v2.HistoryRangeStatus
	(*HistoryRangeResponse)(nil), // 1: webterm.terminal.screen.v2.HistoryRangeResponse
	(*HistoryExtent)(nil),        // 2: webterm.terminal.screen.v2.HistoryExtent
	(*LineData)(nil),             // 3: webterm.terminal.screen.v2.LineData
	(*Dictionary)(nil),           // 4: webterm.terminal.screen.v2.Dictionary
}
var file_shared_proto_terminal_history_proto_depIdxs = []int32{
	0, // 0: webterm.terminal.screen.v2.HistoryRangeResponse.status:type_name -> webterm.terminal.screen.v2.HistoryRangeStatus
	2, // 1: webterm.terminal.screen.v2.HistoryRangeResponse.current_extent:type_name -> webterm.terminal.screen.v2.HistoryExtent
	3, // 2: webterm.terminal.screen.v2.HistoryRangeResponse.lines:type_name -> webterm.terminal.screen.v2.LineData
	4, // 3: webterm.terminal.screen.v2.HistoryRangeResponse.dictionary:type_name -> webterm.terminal.screen.v2.Dictionary
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_terminal_history_proto_init() }
func file_shared_proto_terminal_history_proto_init() {
	if File_shared_proto_terminal_history_proto != nil {
		return
	}
	file_shared_proto_terminal_screen_v2_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_terminal_history_proto_rawDesc), len(file_shared_proto_terminal_history_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_terminal_history_proto_goTypes,
		DependencyIndexes: file_shared_proto_terminal_history_proto_depIdxs,
		EnumInfos:         file_shared_proto_terminal_history_proto_enumTypes,
		MessageInfos:      file_shared_proto_terminal_history_proto_msgTypes,
	}.Build()
	File_shared_proto_terminal_history_proto = out.File
	file_shared_proto_terminal_history_proto_goTypes = nil
	file_shared_proto_terminal_history_proto_depIdxs = nil
}
